version: "3.8"
services:
  os:
    image: amazonlinux

  nginx:
    image: nginx
    depends_on:
      - node
    ports:
      - "443:443"
      - "80:80"
    volumes:
      # Logging
      - ./nginx/log:/var/log/nginx/
      # Volume đến code ứng dụng
      - .:/var/www/app
      # config for ssl if need
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/app
    restart: unless-stopped
    networks:
      - app-network

  mysql:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'laravel'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'

  node:
    image: node
    user: node
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
    ports:
      - "3000:3000"
    tty: true
    restart: unless-stopped
    networks:
      - app-network
    command: 'npm start'

  redis:
    image: redis:3.2


networks:
  app-network:
    driver: bridge